apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/metallb/upstream
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-setup
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/metallb/setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: metallb
